#!/usr/bin/env python3
"""
Interactive Snake Game
"""

import game
import curses_display
import argparse

if __name__ == '__main__':

    available_displays = game.Display.get_available_types()
    available_input_devices = game.InputDevice.get_available_types()

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('-l', '--initial-snake-length', type=int, default=10)
    parser.add_argument('-r', '--restart-after-game-over', action='store_true')
    parser.add_argument('-s', '--speed', type=float, default=10.0)
    parser.add_argument('-d', '--display', choices=available_displays, default='CursesDisplay')
    args = parser.parse_args()

    try:
        while True:
            gm = game.Game(initial_snake_length=args.initial_snake_length)
            with curses_display.CursesDisplay() as display:
                game.run_game_loop(gm, display, display, args.speed)
            print('Your score is {}.'.format(gm.score))
            if not args.restart_after_game_over:
                break
    except KeyboardInterrupt:
        pass

