#!/usr/bin/env python3

import game
import curses_display

if __name__ == '__main__':
    try:
        while True:
            gm = game.Game(initial_snake_length=10)
            gm.step()
            game.run_game_loop(gm, curses_display.CursesDisplay)
    except KeyboardInterrupt:
        pass

